### ISSUE TITLE
Infografía: Obtención de Requerimientos. Fernando Miguel López.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/infografia-Ferch0419-1#1]
[Obtención de requerimientos_Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Ferch0419-1/files/8057320/Obtencion.de.requerimientos_Fernando.Miguel.Lopez.pdf)

**Comment by Abraham890** [comment]
calificación: 20 puntos

**Comment by josealfredo79** [comment]
Super bien hecho y revisado
